addons:
   apt:
      packages:
      - cmake
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - libscalapack-openmpi-dev
   homebrew:
      packages:
      - ninja
      - gcc@10
      - open-mpi
      - scalapack

jobs:
  include:
    - os: linux
      dist: bionic

      language: python
      python: 3.7

      script:
       - mkdir -p _build && pushd _build && cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DEXTERNAL_LIBRARIES="scalapack-openmpi;lapack;blas" .. && make -j && popd

    - os: osx
      osx_image: xcode12
      language: generic

      script:
       - cmake -GNinja -B_build -S. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DEXTERNAL_LIBRARIES="scalapack;lapack;blas" && ninja -C_build

install:
 - pip3 install fypp
